// Code generated by protoc-gen-go. DO NOT EDIT.
// source: idl/eventlog.proto

/*
Package eventlog is a generated protocol buffer package.

It is generated from these files:
	idl/event.proto

It has these top-level messages:
	EventLog
*/
package eventlog

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EventLog_EventType int32

const (
	EventLog_ERROR   EventLog_EventType = 0
	EventLog_WARNING EventLog_EventType = 1
	EventLog_INFO    EventLog_EventType = 2
)

var EventLog_EventType_name = map[int32]string{
	0: "ERROR",
	1: "WARNING",
	2: "INFO",
}
var EventLog_EventType_value = map[string]int32{
	"ERROR":   0,
	"WARNING": 1,
	"INFO":    2,
}

func (x EventLog_EventType) String() string {
	return proto.EnumName(EventLog_EventType_name, int32(x))
}
func (EventLog_EventType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type EventLog struct {
	Version      uint32                     `protobuf:"fixed32,1,opt,name=version" json:"version,omitempty"`
	RecordId     uint64                     `protobuf:"fixed64,2,opt,name=record_id,json=recordId" json:"record_id,omitempty"`
	Source       string                     `protobuf:"bytes,3,opt,name=source" json:"source,omitempty"`
	CreationTime *google_protobuf.Timestamp `protobuf:"bytes,7,opt,name=creation_time,json=creationTime" json:"creation_time,omitempty"`
	Data         string                     `protobuf:"bytes,14,opt,name=data" json:"data,omitempty"`
	//deleted by chen xi
}

func (m *EventLog) Reset()                    { *m = EventLog{} }
func (m *EventLog) String() string            { return proto.CompactTextString(m) }
func (*EventLog) ProtoMessage()               {}
func (*EventLog) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *EventLog) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *EventLog) GetRecordId() uint64 {
	if m != nil {
		return m.RecordId
	}
	return 0
}

func (m *EventLog) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func init() { proto.RegisterFile("idl/eventlog.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 358 bytes of a gzipped FileDescriptorProto
	0x10,
}

// deleted by chenxi
